apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-request-bes
  namespace: myes
spec:
  selector:
    matchLabels:
      run: demo-request-bes
  template:
    metadata:
      labels:
        run: demo-request-bes
    spec:
      containers:
        - image: demo-request-bes:2.0
          name: demo-request-bes
          ports:
            - containerPort: 12002

---
kind: Service
apiVersion: v1
metadata:
  name: demo-request-bes
  namespace: myes
  labels:
    run: demo-request-bes
spec:
  type: NodePort
  selector:
    run: demo-request-bes
  ports:
    - port: 12002
      protocol: TCP
      nodePort: 21992
      targetPort: 12002
