spring:
  application:
    name: service-provider
eureka:
  instance:
    instance-id: service-provider
    hostname: service-provider
  client:
    service-url:
      # eureka地址使用 k8s的service地址
      defaultZone: http://eureka:8080/eureka/
server:
  port: 8080
