server:
  port: 12001
  ioMode: NIO
  bes:
    keep-alive-timeout: -1
    max‑keep‑alive‑requests: -1
spring:
  application:
    name: demo-data-bes
  cloud:
    kubernetes:
      discovery:
        namespaces:
          - myes