server:
  port: 12001
  ioMode: NIO
  bes:
    max‑keep‑alive‑requests: -1
spring:
  application:
    name: demo-data-bes
  cloud:
    kubernetes:
      discovery:
        namespaces:
          - myes