apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-customer
    spec:
      containers:
      - name: service-customer
        image: service-customer
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-customer
spec:
  selector:
    app: service-customer
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
