server:
  port: 12002
  ioMode: NIO
  bes:
    max‑keep‑alive‑requests: -1
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 60000
  httpclient:
    enabled: true # HttpClient的开关
    max-connections: 200  # 最大连接数
    max-connections-per-route: 50   # 单个请求路径的最大连接数
spring:
  application:
    name: demo-request-bes
  cloud:
    kubernetes:
      discovery:
        namespaces:
          - myes
